name: Feature Request
description: Propose a change
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      placeholder: What the change is it trying to solve ?
  - type: textarea
    id: solution
    attributes:
      label: Solution
      placeholder: Can you please give more in details regarding change and the improvement to propose ?
    validations:
      required: true
