name: Feature request
description: Suggest an feature for the project
labels: ["feature"]
body:
  - type: markdown
    attributes: 
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is.
      
  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or screenshots about the feature request here.
