name: Feature request
description: Suggest an feature for the project
labels: ["feature"]
body:
  - type: textarea
    attributes: 
      label: Problem related ?
      description: "Is your feature request related to a problem? Please describe"
      placeholder: "A clear and concise description of what the problem is."
  - type: textarea
    attributes:
      label: Solution
      description: "Describe the solution you'd like"
      placeholder: "A clear and concise description of what you want to happen."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context or screenshots about the feature request here." 
